@startuml

start

:User provides name for search;
:system retrieves the animals;
:system return the sorted animals;
if (Animal found) then (yes)
   : receives OK message;
else (Animal not found)
   : receives Not Found message;
endif

@enduml







