@startuml

start
:User retries all animals sorted by name;
:system retrieves the animals;
:system get all animals
:system sorts the animals  by name;
:system return the sorted animals;

stop

@enduml


get : sort : return




