|@startuml

@startuml

User -> AnimalShelterApp : provides name for search
AnimalShelterApp -> AnimalService : findAnimalByName(name)
AnimalService -> AnimalRepository : findAnimalByName(name)
AnimalService <-- AnimalRepository : Animal
AnimalShelterApp <-- AnimalService : Animal details or Not Found message
@enduml





@startuml

User -> AnimalShelterApp : provides name for search
AnimalShelterApp -> AnimalService : findAnimalByName(name)
AnimalService -> AnimalRepository : findAnimalByName(name)
AnimalService <-- AnimalRepository : Animal

alt Animal found
    AnimalShelterApp <-- AnimalService : Animal details
else Animal not found
    AnimalShelterApp <-- AnimalService : Not Found message
end

@enduml






@startuml

User -> AnimalShelterApp : requests all animals sorted by name
AnimalShelterApp -> AnimalService : getAllAnimalsSortedByName()
AnimalService -> AnimalRepository : getAnimals()
AnimalService <-- AnimalRepository : List<Animal>
AnimalService -> AnimalService : sortAnimalsByName(List<Animal>)
AnimalShelterApp <-- AnimalService : List of animals sorted by name
@enduml


