|@startuml

@startuml

User -> AnimalShelterApp : provides name for search
AnimalShelterApp -> AnimalService : findAnimalByName(name)
AnimalService -> AnimalRepository : findAnimalByName(name)
AnimalService <-- AnimalRepository :List< Animal>
AnimalShelterApp <-- AnimalService : Animal details or Not Found message
alt found  yes- return message
else  no
end
@enduml














